### PR TITLE
add refreshing browser while tasks running support

### LINKED ISSUE #6: Refreshing the dashboard with background tasks
Hey, 

It's me again 😄 

One little problem (is it ?) is when running a background task (like `dev` server) and then refreshing the dashboard, the task doesn't seem to be running anymore. Even if it's still running in the background. The only way to `kill` it is manually with the pid or exiting webdash (not a problem)

### PR DESCRIPTION
**Pull request by bardiarastin**
closes #6

### CODE REVIEW

**Comment by jadjoubran** [comment]
That's on reload 😄 
scripts

**Comment by bardiarastin** [comment]
currently this does keep running scripts in localstorage but not adding spinner to buttons

**Comment by jadjoubran** [comment]
Yep, I implemented it
and now I'm figuring out how to push it to your repo as part of the same PR

**Comment by jadjoubran** [comment]
can you add me as a contributor on your git@github.com:bardiarastin/webdash-npm-scripts.git so I can push to it? (or tell me if you know of a better way)

**Comment by jadjoubran** [comment]
Another approach would be that I sent you a PR
I'm sure I messed up somewhere 😅 and there must be an easier way to amend the PR

**Comment by bardiarastin** [comment]
sorry for delay, i've merged your pull request to my repo

**Comment by bardiarastin** [comment]
i guess we did not need pull request
image

**Pull request merged**
